version: 2

sources:
  - name: src
    description: Data sources from redshift
    schema: wnsldjqja
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 1, period: day}
    loaded_at_field: created_at

    tables:
      - name: tour_api
        description: 관광지 방문 현황 테이블 by 한국관광공단 API
        identifier: tourism

      - name: weather_api
        description: 지역별,시간별 날씨 테이블 by 기상청 API
        identifier: weather_info

      - name: tourist_spot
        description: 관광지 지역 정보 테이블 by 국토 교통부
        identifier: tourist_spot

      - name: signgu
        description: 시/군/구 테이블 by SGIS
        identifier: signgu

      - name: korea_dept
        description: 지역 코드 테이블 by SGIS
        identifier: korea_dept
